using HarmonyLib;
using Il2Cpp;
using MelonLoader;

#pragma warning disable CS8603

namespace TweaksAndFixes
{
    [HarmonyPatch(typeof(CampaignNewGame))]
    internal class Patch_CampaignNewGame
    {
        internal const int FleetCreationAutoGenerated = 0;
        internal const int FleetCreationCreateOwn = 1;
        internal const int FleetCreationBlankSlate = 2;
        private const int FleetCreationOptionCount = 3;

        internal static bool BlankSlateCampaignSelected { get; private set; } = false;
        internal static int CurrentFleetCreationOption { get; private set; } = FleetCreationAutoGenerated;

        private static int WrapFleetCreationIndex(int index)
        {
            if (index < 0)
                return FleetCreationOptionCount - 1;

            if (index >= FleetCreationOptionCount)
                return 0;

            return index;
        }

        private static string FleetCreationOptionLocKey(int index)
        {
            return index switch
            {
                FleetCreationAutoGenerated => "$Ui_NewGame_AutoGenerated",
                FleetCreationCreateOwn => "$Ui_NewGame_CreateOwn",
                FleetCreationBlankSlate => "$TAF_Ui_NewGame_BlankSlate",
                _ => "$Ui_NewGame_AutoGenerated",
            };
        }

        private static string FleetCreationOptionName(int index)
        {
            return index switch
            {
                FleetCreationAutoGenerated => "Auto-Generated",
                FleetCreationCreateOwn => "Create Own",
                FleetCreationBlankSlate => "Blank Slate",
                _ => "Auto-Generated",
            };
        }

        internal static void SetFleetCreationOption(CampaignNewGame cng, int index)
        {
            if (cng == null)
                return;

            cng.fleetCreation = WrapFleetCreationIndex(index);
            SetFleetCreationText(cng);
            UpdateBlankSlateSelection(cng);
        }

        private static void SetFleetCreationText(CampaignNewGame cng)
        {
            if (cng?.FleetCreation == null)
                return;

            string option = LocalizeManager.Localize(FleetCreationOptionLocKey(cng.fleetCreation));
            cng.FleetCreation.text = LocalizeManager.Localize("$Ui_NewGame_FleetCreation", option);
        }

        private static void UpdateBlankSlateSelection(CampaignNewGame cng)
        {
            CurrentFleetCreationOption = WrapFleetCreationIndex(cng?.fleetCreation ?? FleetCreationAutoGenerated);
            bool selected = CurrentFleetCreationOption == FleetCreationBlankSlate;
            if (BlankSlateCampaignSelected == selected)
                return;

            BlankSlateCampaignSelected = selected;
            if (selected)
                Melon<TweaksAndFixes>.Logger.Msg("New campaign fleet creation: Blank Slate selected; pre-start ship generation will be skipped.");
        }

        internal static void LogCampaignStartFleetCreation(bool createOwnFleet)
        {
            bool blankSlate = CurrentFleetCreationOption == FleetCreationBlankSlate && !createOwnFleet;
            BlankSlateCampaignSelected = blankSlate;
            Melon<TweaksAndFixes>.Logger.Msg($"New campaign start fleet creation: {FleetCreationOptionName(CurrentFleetCreationOption)}, createOwnFleet={createOwnFleet}, blankSlate={blankSlate}.");
        }

        internal static bool FixDesignUsage(CampaignNewGame cng)
        {
            if (!Config.ForceNoPredefsInNewGames)
                return false;

            cng.campaignDesignsUsage = 0;
            cng.DesignUsage.text = LocalizeManager.Localize($"$Ui_NewGame_DesignUsage_{(CampaignController.DesignsUsage)cng.campaignDesignsUsage}");
            return true;
        }

        [HarmonyPatch(nameof(CampaignNewGame.Show))]
        [HarmonyPrefix]
        internal static void Prefix_Show(CampaignNewGame __instance)
        {
            __instance.fleetCreation = FleetCreationCreateOwn;
            CurrentFleetCreationOption = FleetCreationCreateOwn;
            BlankSlateCampaignSelected = false;
            FixDesignUsage(__instance);
        }

        [HarmonyPatch(nameof(CampaignNewGame.ChangeFleetCreation))]
        [HarmonyPrefix]
        internal static bool Prefix_ChangeFleetCreation(CampaignNewGame __instance, int moveTo)
        {
            SetFleetCreationOption(__instance, __instance.fleetCreation + moveTo);
            return false;
        }

        [HarmonyPatch(nameof(CampaignNewGame.ChangeDesignUsage))]
        [HarmonyPrefix]
        internal static bool Prefix_ChangeDesignUsage(CampaignNewGame __instance)
        {
            return !FixDesignUsage(__instance);
        }
    }
}
